### ISSUE TITLE
not working on terminal 1.2+

### ISSUE THREAD

**Issue by BlueOnBLack** [german-one/termwnd#1]
on 1.8+ it works fine
previous release ... not

**Comment by german-one** [comment]
> on 1.8+ it works fine
previous release ... not

Thank you for your feedback!  

I tested the code on Windows 11 (10.0.22621.1848) using the current stable version of Windows Terminal v1.17.11461.0, and the current preview v1.18.1462.0. Besides of that I tested in the v2 Console as well as in the Legacy Console Host.  

You mentioned versions 1.2 and 1.8 which would be obsolete for years. Refer to:  
https://github.com/microsoft/terminal/releases  
So it seems that those version numbers belong to a 3rd party terminal (which would not be supported as stated in the documentation of this repository).  

If you referred to the "Windows Terminal" (and not to a 3rd party terminal app) I'd like to know:  
1. the Windows version you've been running the code  
2. the actual Windows Terminal version you tested the code  
3. since I provided the code in 6 different programming languages, which of them did you test  
4. what does "not working" actually mean (what's been your expectation and what happened instead)  

Thanks in advance!

**Comment by BlueOnBLack** [comment]
use the original terminal package from Windows 11
and PS1 version ...
the original version you suppresses working fine
the new version does not show any details ... 
it fail to get them

**Comment by BlueOnBLack** [comment]
another image

![image](https://github.com/german-one/termwnd/assets/114880512/1fd89668-8f9a-4f4b-a559-cf1c92ac7092)

**Comment by german-one** [comment]
I'm afraid I can not reproduce it anymore since v1.12 is obsolete for more than a year now, and I don't know what the terminal team changed on the process model in the meanwhile. Try if updating to a more recent version solves this issue for you.

**Comment by BlueOnBLack** [comment]
As I said ... original version worked fine
the new one not supported v12 anymore
something was changed

**Comment by german-one** [comment]
The whole point for writing the new code was to reflect the changed process model in Windows Terminal v.1.18. I'm sorry if this isn't backward compatible to those old versions anymore. However, it should still work on the current stable version v.17. At least it does in my tests.

**Comment by german-one** [comment]
I tried to find related PRs in the Terminal repo.  
https://github.com/microsoft/terminal/pull/12526  
https://github.com/microsoft/terminal/issues/12911  
Since the new code relies on the hidden ConPTY window being owned by the Terminal window, presumably all versions which contain these commits are still supported.  

I have no good idea of how to work around it without breaking the support for 1.18. So I think I can't fix the code for even older versions.
